version: 2
jobs:
  build:
    working_directory: ~/my-app

    docker:
      - image: node:6.10.0

    steps:
      - add-ssh-keys:
          fingerprints:
            - "c6:f7:c8:85:70:d5:1f:5d:2c:fb:09:6d:c6:e4:7e:c3"

      - checkout

      - run:
          name: Pre-Dependencies
          command: mkdir -p ~/my-app/build
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test -- --coverage
          
      - store_artifacts:
          path: ~/my-app/build
          destination: coverage

      # Deploy production
      - deploy:
          command: ./scripts/publish.sh;
            
