version: 2
jobs:
  build:
    working_directory: ~/my-app

    docker:
      - image: node:6.10.0

    steps:
      - add-ssh-keys:
          fingerprints:
            - "58:dd:d1:ca:4e:78:eb:74:f9:08:cb:93:08:f6:e9:76"

      - checkout

      - run:
          name: Pre-Dependencies
          command: mkdir -p ~/my-app/build
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test -- --coverage
          
      - store_artifacts:
          path: ~/my-app/build
          destination: coverage

      # Deploy production
      - deploy:
          command: ./scripts/publish.sh ;
            
