version: 2
jobs:
  build:
    working_directory: ~/my-app

    docker:
      - image: node:6.10.0

    steps:
      - add-ssh-keys:
          fingerprints:
            - "7c:e5:e0:30:72:5b:42:9e:41:12:7c:a5:0b:dc:68:8f"

      - checkout

      - run:
          name: Pre-Dependencies
          command: mkdir -p ~/my-app/build
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test -- --coverage
          
      - store_artifacts:
          path: ~/my-app/build
          destination: coverage

      # Deploy production
      - deploy:
          command: ./scripts/publish.sh ;
            
