version: 2
jobs:
  build:
    working_directory: ~/my-app

    docker:
      - image: node:6.10.0

    steps:
      - add-ssh-keys:
          fingerprints:
            - "01:e1:1e:07:2c:10:5c:b4:24:8e:4f:2f:87:dc:1c:6d"

      - checkout

      - run:
          name: Pre-Dependencies
          command: mkdir -p ~/my-app/build
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test
          
      - store_artifacts:
          path: ~/my-app/build
          destination: coverage

      # Deploy production
      - deploy:
          command: ./scripts/publish.sh ;
            
